<a href="https://colab.research.google.com/github/mrzResearchArena/Karpathy/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(f'PyTorch Version: {torch.__version__}.')
# It does not work. However, it has been kept here for testing.
# torch.set_default_dtype(torch.float)


device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f'We\'re using "{device}" as device.')
# SET GPU/TPU: Runtime (Tab) → Change Runtime Type → GPU.


torch.manual_seed(1337)
# SET random seed is 1337; Andrej Karpathy uses 1337 as seed.

import numpy as np
np.random.seed(1337)

PyTorch Version: 2.1.0+cu121.
We're using "cpu" as device.


### 1. Tensor Computation:
---

### 1.x Mathematics:
---

In [ ]:
print(np.math.factorial(5))
print(torch.math.factorial(5))

120
120


In [ ]:
v = torch.tensor(1)

print(torch.exp(v).item())

2.7182817459106445
2.718281828459045


### 1.1 begin:

In [ ]:
help(torch.set_default_dtype)

Help on function set_default_dtype in module torch:

set_default_dtype(d)
    Sets the default floating point dtype to :attr:`d`. Supports torch.float32
    and torch.float64 as inputs. Other dtypes may be accepted without complaint
    but are not supported and are unlikely to work as expected.
    
    When PyTorch is initialized its default floating point dtype is torch.float32,
    and the intent of set_default_dtype(torch.float64) is to facilitate NumPy-like
    type inference. The default floating point dtype is used to:
    
    1. Implicitly determine the default complex dtype. When the default floating point
       type is float32 the default complex dtype is complex64, and when the default
       floating point type is float64 the default complex type is complex128.
    2. Infer the dtype for tensors constructed using Python floats or complex Python
       numbers. See examples below.
    3. Determine the result of type promotion between bool and integer tensors and
       Py

In [ ]:
torch.set_default_dtype(torch.float64)

x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=float)

y = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=float)

z = torch.matmul(x, y)
print(z)

print(x.dtype) ## property (getter) → def dtype(self,): return type(~).

print(type(x))

print(x.shape) #print(x.size())

tensor([[22., 28.],
        [49., 64.]])
torch.float64
<class 'torch.Tensor'>
torch.Size([2, 3])


### 1.x. `arange() and linspace():`
---

In [ ]:
v = torch.arange(start=-5, end=5+1, step=1.0) # step (float)
print(v)

# v = np.arange(start=-5, stop=5+1, step=1.0) # step (float)

# https://pytorch.org/docs/stable/generated/torch.arange.html

v = torch.linspace(start=-5, end=5, steps=11) # steps (int)
print(v)
# https://pytorch.org/docs/stable/generated/torch.linspace.html

tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])
tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])


In [ ]:
# help(torch.linspace)

In [ ]:
h = 0.1
x_test = torch.arange(start=-1, end=1+h, step=h)
print(x_test)

t_test = torch.arange(start=0, end=1+h, step=h)
print(t_test)

tensor([-1.0000e+00, -9.0000e-01, -8.0000e-01, -7.0000e-01, -6.0000e-01,
        -5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
         5.5511e-17,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,
         5.0000e-01,  6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,
         1.0000e+00])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


### 1.x. `ones(), zeros(), randn():`
---



In [ ]:
v = torch.ones(size=(2, 3)) # format-1 (allowed)
print(v)
# Generate "ones": rows (m) x columns (n)
# --------------------------------------:
# v = torch.ones((2, 3)) # format-2 (allowed)
# v = torch.ones(2, 3)   # format-3 (allowed)
# It is preferred to use "format-1."




v = torch.ones(size=(2,)) # format-1 (allowed)
print(v)
# Generate "ones": columns (n)
# ---------------------------:
# v = torch.ones(size=(2)) # format-2 (NOT allowed): argument 'size' must be tuple of ints, not int.
# v = torch.ones((2,))     # format-3 (allowed)
# v = torch.ones(2,)       # format-4 (allowed)
# v = torch.ones(2)        # format-5 (allowed)
# It is preferred to use "format-1."

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 1.])


In [ ]:
v = torch.ones(size=(2, 3)) # format-1 (good practice)
print(v)

v = torch.ones(size=(2,)) # format-2 (good practice)
print(v)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 1.])


In [ ]:
# Note: "zeros" are the exact same formats like "ones"
v = torch.zeros(size=(2, 3)) # format-1 (good practice)
print(v)

v = torch.zeros(size=(2,)) # format-2 (good practice)
print(v)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# Note: "randn" are the exact same formats like  "ones" and "zeros".
v = torch.randn(size=(2, 3)) # "standard normal distribution" with mean `0` and variance `1`.
print(v)
# print(sum(v))

v = torch.randn(size=(2,)) # "standard normal distribution" with mean `0` and variance `1`.
print(v)

tensor([[ 0.1378, -0.3889,  0.5133],
        [ 0.3319,  0.6300,  0.5815]])
tensor([-0.0282, -0.1744])


### 1.x. make `ones_like(), zeros_like()` shaped tensors:

In [ ]:
v = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])


v = torch.ones_like(v)
print(v)


v = torch.zeros_like(v)
print(v)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [ ]:
###

### 1.x. Gradient:

In [ ]:
x = torch.tensor([1, 2, 3])
# x.requires_grad_(True)
print(x)

# Methond-1: Requires Grad – outside tensor
x = torch.tensor([1, 2, 3], dtype=float).requires_grad_(True)
print(x)

# Methond-2: Requires Grad – inside tensor
x = torch.tensor([1, 2, 3], dtype=float, requires_grad=True)
print(x)

# Methond-3: Requires Grad – next-line
x = torch.tensor([1, 2, 3], dtype=float)
x.requires_grad = True
print(x)

# Note: However, the data type should be float (i.e., "dtype=float"); otherwise, gradient does not work.

tensor([1, 2, 3])
tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)
tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)
tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)


In [ ]:
# a = torch.tensor([2., 3.], requires_grad=True)
# b = torch.tensor([6., 4.], requires_grad=True)

# Q = (3*(a**3)) - (b**2)

# external_grad = torch.tensor([1., 1.])
# Q.backward(gradient=external_grad)

# Q.backward(gradient=external_grad)

In [ ]:
x=torch.tensor([3.], requires_grad=True, dtype=float) # dtype=float
y = x**3

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

y.backward()
print(x.grad)

tensor([27.], dtype=torch.float64)
tensor([54.], dtype=torch.float64)
tensor([81.], dtype=torch.float64)
tensor([108.], dtype=torch.float64)


In [ ]:
a=torch.tensor([2.0,], requires_grad=True)
b=torch.tensor([3.0,], requires_grad=True)

def F(a, b):
    return a**4.0 + 2*b**2
#end-def

y = F(a, b)

F1a = torch.autograd.grad(y, a, create_graph=True)
F1b = torch.autograd.grad(y, b, create_graph=True)

print(F1a[0].item())
print(F1b[0].item())

# F2 = torch.autograd.grad(F1, x, create_graph=True)

# print(F2[0].item())

# F3 = torch.autograd.grad(F2, x, create_graph=True)

# print(F3[0].item())

# F4 = torch.autograd.grad(F3, x, create_graph=True)

# print(F4[0].item())

# F5 = torch.autograd.grad(F4, x, create_graph=True)

# print(F5[0].item())

32.0
12.0


In [ ]:
x=torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], requires_grad=True)

def F(x):
    return (x**4.0) + (2*(x**3))
#end-def

y = F(x)
print(y)

F1 = torch.autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
print(F1)


F2 = torch.autograd.grad(F1, x, torch.ones_like(F1), create_graph=True)[0]
print(F2)


F3 = torch.autograd.grad(F2, x, torch.ones_like(F2), create_graph=True)[0]
print(F3)


F4 = torch.autograd.grad(F3, x, torch.ones_like(F3), create_graph=True)[0]
print(F4)


F5 = torch.autograd.grad(F4, x, torch.ones_like(F4), create_graph=True)[0]
print(F5)

tensor([  3.,  32., 135., 384., 875.], grad_fn=<AddBackward0>)
tensor([ 10.,  56., 162., 352., 650.], grad_fn=<AddBackward0>)
tensor([ 24.,  72., 144., 240., 360.], grad_fn=<AddBackward0>)
tensor([ 36.,  60.,  84., 108., 132.], grad_fn=<AddBackward0>)
tensor([24., 24., 24., 24., 24.], grad_fn=<AddBackward0>)
tensor([0., 0., 0., 0., 0.])


In [ ]:
x=torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], requires_grad=True)

def F(x):
    return (x)
#end-def

y = F(x)
print(y)

F1 = torch.autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
print(F1)

tensor([1., 2., 3., 4., 5.], requires_grad=True)
tensor([1., 1., 1., 1., 1.])


tensor([-1.0000e+00, -9.0000e-01, -8.0000e-01, -7.0000e-01, -6.0000e-01,
        -5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
        -2.9802e-09,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,
         5.0000e-01,  6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,
         1.0000e+00])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [ ]:
# help(torch.arange)

### 1.x. `vstack() and hstack()`

In [ ]:
# https://pytorch.org/docs/stable/generated/torch.vstack.html

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

v = torch.vstack((a,b))
print(v)

a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])

v = torch.vstack((a,b))
print(v)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [ ]:
# https://pytorch.org/docs/stable/generated/torch.hstack.html

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

v = torch.hstack((a,b))
print(v)

a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])

v = torch.hstack((a,b))
print(v)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

v = torch.stack((a,b), dim=0) #vertical-stack
print(v)

v = torch.stack((a,b), dim=1) #right-90°
print(v)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
help(torch.stack)

Help on built-in function stack in module torch:

stack(...)
    stack(tensors, dim=0, *, out=None) -> Tensor
    
    Concatenates a sequence of tensors along a new dimension.
    
    All tensors need to be of the same size.
    
    .. seealso::
    
        :func:`torch.cat` concatenates the given sequence along an existing dimension.
    
    Arguments:
        tensors (sequence of Tensors): sequence of tensors to concatenate
        dim (int): dimension to insert. Has to be between 0 and the number
            of dimensions of concatenated tensors (inclusive)
    
    Keyword args:
        out (Tensor, optional): the output tensor.



### 1.x: `squeeze(), unsqueeze():`
---

*   squeeze: https://pytorch.org/docs/stable/generated/torch.squeeze.html
*   unsqueeze: https://pytorch.org/docs/stable/generated/torch.unsqueeze.html
---



In [ ]:
# v = torch.tensor([
#     [1, 2, 3],
#     [4, 5, 6]
# ])

v = torch.tensor([
    [1],
    [2],
    [3],
    [4],
    [5],
])

print(v)

v = v.squeeze(dim=0)
print(v)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


### Miscellaneous:

In [ ]:
A = torch.tensor(1.0, requires_grad=True)
B = torch.tensor(2.0, requires_grad=True)
C = torch.tensor(3.0, requires_grad=True)
D = torch.tensor(4.0, requires_grad=True)

epochs = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(epochs):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
#end-for

print(A)
print(B)
print(C)
print(D)

tensor(4.0000, requires_grad=True)
tensor(5.0000, requires_grad=True)
tensor(4.0000, requires_grad=True)
tensor(3.0000, requires_grad=True)


In [ ]:
torch.randn(size=(1,)).squeeze()

tensor(0.6889)

In [ ]:
np.random.randn(1,).squeeze()

array(-0.18211348)

In [ ]:
import random
random.rand()

AttributeError: ignored

In [ ]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

a[1,1]=50

print(a)

b = a

print(b)

tensor([[ 1,  2,  3],
        [ 4, 50,  6]])
tensor([[ 1,  2,  3],
        [ 4, 50,  6]])


In [ ]:
 def loss_function(self,):
 	#zero the parameter gradients:
	optimizer.zero_grad()

	#forward pass:
    y_pred = self.model(self.X_train)
    loss = criterion(y_pred, y_train)

    #backward pass and optimize:
	loss.backward()
    optimizer.step()
#end-def

IndentationError: ignored

In [ ]:
v = torch.tensor([1.0])
print(v.item())
print(v.tolist())

# https://pytorch.org/docs/stable/generated/torch.Tensor.item.html
# https://pytorch.org/docs/stable/generated/torch.Tensor.tolist.html#torch.Tensor.tolist

1.0
[1.0]


In [ ]:
import numpy as np
v = np.array([
    [1, 2, 3],
    [4, 5, 6],
], dtype=float)

print(v)
v = torch.tensor(v)
print(v)

[[1. 2. 3.]
 [4. 5. 6.]]
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
